# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-north-1
  environment:
    DYNAMODB_PRODUCTS_TABLE: ProductsDB
    DYNAMODB_STOCK_TABLE: StockDB
    REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_PRODUCTS_TABLE}"
            - "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_STOCK_TABLE}"

plugins:
  - serverless-offline

functions:
  getProductsList:
    handler: handlers/get-product-list.getProductsList
    events:
      - http:
          path: products
          method: get
  getProductsById:
    handler: handlers/get-product.getProductsById
    events:
      - http:
          path: products/{productId}
          method: get
  createProduct:
    handler: handlers/create-product.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true